[[constraint]]
  name = "github.com/spf13/cobra"
  version = "1.1.3"

[[constraint]]
  name = "github.com/sarulabs/di"
  version = "v2.4.0"

[[constraint]]
  name = "github.com/stevenroose/gonfig"
  version = "0.1.5"

[[constraint]]
  name = "github.com/sepuka/vkbotserver"
  version = "v0.0.3"