[[constraint]]
  name = "github.com/spf13/cobra"
  version = "1.1.3"

[[constraint]]
  name = "github.com/sarulabs/di"
  version = "v2.4.0"

[[constraint]]
  name = "github.com/stevenroose/gonfig"
  version = "0.1.5"

[[constraint]]
  name = "github.com/sepuka/vkbotserver"
  #version = "v0.0.6"
  branch = "main"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.16.0"

[[constraint]]
  name = "github.com/go-pg/pg"
  version = "v8.0.7"

[[constraint]]
  name = "github.com/golang/text"
  version = "v0.3.5"